#!/usr/bin/env node
/**
 * SHADER INLINER
 * 
 * Pre-build script that reads all .glsl, .vert, .frag files in /src/shaders/
 * and inlines them as string literals in /src/lib/three/shaderLoader.ts.
 * 
 * This avoids runtime fetch calls in production and enables proper
 * tree-shaking of unused shaders.
 * 
 * Run automatically before build via package.json scripts:
 *   "prebuild": "node scripts/inline-shaders.mjs"
 */

import { readFileSync, writeFileSync, readdirSync, statSync, existsSync } from "node:fs";
import { join, relative, sep, basename } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = fileURLToPath(new URL(".", import.meta.url));
const ROOT = join(__dirname, "..");
const SHADERS_DIR = join(ROOT, "src", "shaders");
const LOADER_FILE = join(ROOT, "src", "lib", "three", "shaderLoader.ts");

function walkDir(dir) {
  const results = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const stat = statSync(full);
    if (stat.isDirectory()) {
      results.push(...walkDir(full));
    } else if (/\.(glsl|vert|frag)$/.test(entry)) {
      results.push(full);
    }
  }
  return results;
}

function processIncludes(source, filename) {
  const includeRegex = /#include\s+(.+?)(?:\n|$)/g;
  return source.replace(includeRegex, (match, includePath) => {
    const trimmed = includePath.trim().replace(/["']/g, "");
    const currentDir = filename.split("/").slice(0, -1).join("/");
    const resolvedPath = join(SHADERS_DIR, currentDir, trimmed);
    if (existsSync(resolvedPath)) {
      const includeContent = readFileSync(resolvedPath, "utf-8");
      return processIncludes(includeContent, resolvedPath.replace(ROOT + sep, ""));
    }
    return `// #include "${trimmed}" — NOT FOUND`;
  });
}

function main() {
  if (!existsSync(SHADERS_DIR)) {
    console.log("[inline-shaders] No shaders directory, skipping");
    return;
  }

  const files = walkDir(SHADERS_DIR);
  const inlined = {};

  for (const file of files) {
    const rel = relative(SHADERS_DIR, file).replace(/\\/g, "/");
    let content = readFileSync(file, "utf-8");
    // Remove #include directives by inlining them
    content = processIncludes(content, rel);
    inlined[rel] = content;
  }

  // Generate the loader file content
  const header = `/**
 * AUTO-GENERATED by scripts/inline-shaders.mjs
 * DO NOT EDIT — Edit the .glsl/.vert/.frag files in /src/shaders/ instead
 * Generated: ${new Date().toISOString()}
 */

export const INLINED_SHADERS: Record<string, string> = {`;

  const body = Object.entries(inlined)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([name, content]) => {
      // Escape template literal characters
      const escaped = content
        .replace(/\\/g, "\\\\")
        .replace(/`/g, "\\`")
        .replace(/\$\{/g, "\\${");
      return `\n  "${name}": \`${escaped}\`,`;
    })
    .join("");

  const footer = `\n};\n`;

  const fullContent = header + body + footer;

  writeFileSync(LOADER_FILE, fullContent);
  console.log(`[inline-shaders] Inlined ${Object.keys(inlined).length} shader files`);
}

main();
