#!/usr/bin/env python3
"""OKLCH -> sRGB hex + WCAG contrast verification for the Imaginars dual-mode palette.

Run:  python3 palette.py
Every hex in the design spec is generated by this file. Re-run after any token change.
"""
import math

# ---------- OKLCH -> sRGB ----------

def oklch_to_linear(L, C, H):
    h = math.radians(H)
    a = C * math.cos(h)
    b = C * math.sin(h)
    l_ = L + 0.3963377774 * a + 0.2158037573 * b
    m_ = L - 0.1055613458 * a - 0.0638541728 * b
    s_ = L - 0.0894841775 * a - 1.2914855480 * b
    l, m, s = l_ ** 3, m_ ** 3, s_ ** 3
    r = 4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s
    g = -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s
    bl = -0.0041960863 * l - 0.7034186147 * m + 1.7076147010 * s
    return r, g, bl


def encode(c):
    c = max(0.0, min(1.0, c))
    return 12.92 * c if c <= 0.0031308 else 1.055 * (c ** (1 / 2.4)) - 0.055


def in_gamut(L, C, H, tol=1e-4):
    return all(-tol <= v <= 1 + tol for v in oklch_to_linear(L, C, H))


def max_chroma(L, H, hi=0.45):
    lo = 0.0
    for _ in range(40):
        mid = (lo + hi) / 2
        if in_gamut(L, mid, H):
            lo = mid
        else:
            hi = mid
    return lo


def fit_chroma(L, C, H, headroom=0.98):
    return min(C, max_chroma(L, H) * headroom)


def oklch_hex(L, C, H):
    r, g, b = (encode(v) for v in oklch_to_linear(L, C, H))
    return "#%02X%02X%02X" % tuple(round(v * 255) for v in (r, g, b))


# ---------- WCAG ----------

def hex_rgb(h):
    h = h.lstrip("#")
    return tuple(int(h[i:i + 2], 16) / 255 for i in (0, 2, 4))


def luminance(h):
    def lin(c):
        return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4
    r, g, b = (lin(c) for c in hex_rgb(h))
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def contrast(a, b):
    la, lb = luminance(a), luminance(b)
    hi, lo = max(la, lb), min(la, lb)
    return (hi + 0.05) / (lo + 0.05)


# ---------- Ramps ----------

HUE_BRAND = 265.0
HUE_NEUTRAL = 265.0

NEUTRAL = {
    "50":  (0.985, 0.0035), "100": (0.966, 0.005), "200": (0.925, 0.007),
    "300": (0.872, 0.009),  "400": (0.715, 0.013), "500": (0.600, 0.016),
    "600": (0.505, 0.016),  "700": (0.408, 0.015), "800": (0.300, 0.014),
    "900": (0.212, 0.013),  "950": (0.140, 0.012),
}

BRAND = {
    "50":  (0.965, 0.018), "100": (0.935, 0.040), "200": (0.878, 0.075),
    "300": (0.800, 0.115), "400": (0.712, 0.155), "500": (0.628, 0.190),
    "600": (0.548, 0.205), "700": (0.472, 0.186), "800": (0.398, 0.150),
    "900": (0.330, 0.112), "950": (0.235, 0.072),
}

SEMANTIC = {
    "success-light": (0.520, 0.130, 158.0),
    "success-dark":  (0.760, 0.145, 158.0),
    "warning-light": (0.560, 0.135, 68.0),
    "warning-dark":  (0.800, 0.150, 78.0),
    "danger-light":  (0.545, 0.190, 25.0),
    "danger-dark":   (0.720, 0.165, 25.0),
}


def build(ramp, hue, label=""):
    out = {}
    for k, (L, C) in ramp.items():
        Cf = fit_chroma(L, C, hue)
        if abs(Cf - C) > 0.0005:
            print(f"  {label}{k}: chroma tapered {C:.3f} -> {Cf:.3f} to stay in sRGB")
        out[k] = oklch_hex(L, Cf, hue)
    return out


n = build(NEUTRAL, HUE_NEUTRAL, "neutral-")
b = build(BRAND, HUE_BRAND, "brand-")
s = {k: oklch_hex(v[0], fit_chroma(*v), v[2]) for k, v in SEMANTIC.items()}

LIGHT = {
    "bg":            n["50"],
    "surface":       "#FFFFFF",
    "surface-raised": "#FFFFFF",
    "surface-sunken": n["100"],
    "text":          n["950"],
    "text-muted":    n["700"],
    "text-subtle":   n["600"],
    "border-hairline": n["200"],
    "border":        n["300"],
    "border-interactive": n["500"],
    "accent":        b["600"],
    "accent-hover":  b["700"],
    "accent-fg":     "#FFFFFF",
    "accent-subtle": b["50"],
    "focus-ring":    b["600"],
    "success":       s["success-light"],
    "warning":       s["warning-light"],
    "danger":        s["danger-light"],
}

DARK = {
    "bg":            n["950"],
    "surface":       oklch_hex(0.185, 0.014, HUE_NEUTRAL),
    "surface-raised": oklch_hex(0.228, 0.015, HUE_NEUTRAL),
    "surface-sunken": oklch_hex(0.115, 0.011, HUE_NEUTRAL),
    "text":          oklch_hex(0.945, 0.006, HUE_NEUTRAL),
    "text-muted":    n["400"],
    "text-subtle":   n["500"],
    "border-hairline": oklch_hex(0.280, 0.014, HUE_NEUTRAL),
    "border":        oklch_hex(0.360, 0.015, HUE_NEUTRAL),
    "border-interactive": oklch_hex(0.545, 0.016, HUE_NEUTRAL),
    "accent":        b["400"],
    "accent-hover":  b["300"],
    "accent-fg":     oklch_hex(0.180, 0.030, HUE_BRAND),
    "accent-subtle": oklch_hex(0.270, 0.055, HUE_BRAND),
    "focus-ring":    b["400"],
    "success":       s["success-dark"],
    "warning":       s["warning-dark"],
    "danger":        s["danger-dark"],
}


def ramp_table(name, r):
    print(f"\n{name}")
    for k, v in r.items():
        print(f"  {k:>4}  {v}")


ramp_table("NEUTRAL (hue 265, tinted)", n)
ramp_table("BRAND / indigo (hue 265)", b)
print("\nSEMANTIC")
for k, v in s.items():
    print(f"  {k:>14}  {v}")

PAIRS = [
    ("text", "bg", 4.5), ("text", "surface", 4.5), ("text", "surface-raised", 4.5),
    ("text-muted", "bg", 4.5), ("text-muted", "surface", 4.5),
    ("text-subtle", "bg", 4.5), ("text-subtle", "surface", 4.5),
    ("accent", "bg", 4.5), ("accent", "surface", 4.5),
    ("accent-hover", "bg", 4.5),
    ("accent-fg", "accent", 4.5), ("accent-fg", "accent-hover", 4.5),
    ("border-hairline", "bg", 1.0),
    ("border", "bg", 1.0),
    ("border-interactive", "bg", 3.0), ("border-interactive", "surface", 3.0),
    ("focus-ring", "bg", 3.0), ("focus-ring", "surface", 3.0),
    ("success", "bg", 4.5), ("warning", "bg", 4.5), ("danger", "bg", 4.5),
    ("success", "surface", 4.5), ("warning", "surface", 4.5), ("danger", "surface", 4.5),
    ("accent", "accent-subtle", 4.5),
    ("text", "accent-subtle", 4.5),
]

failures = []
for mode, tokens in (("LIGHT", LIGHT), ("DARK", DARK)):
    print(f"\n=== {mode} MODE ===")
    for k, v in tokens.items():
        print(f"  --color-{k:<15} {v}")
    print(f"\n  contrast checks ({mode})")
    for fg, bgk, target in PAIRS:
        ratio = contrast(tokens[fg], tokens[bgk])
        ok = ratio >= target
        flag = "PASS" if ok else "FAIL"
        if not ok:
            failures.append((mode, fg, bgk, round(ratio, 2), target))
        print(f"    {fg:>14} on {bgk:<15} {ratio:6.2f}:1  need {target:>4}  {flag}")

print("\n---")
if failures:
    print(f"{len(failures)} FAILURE(S):")
    for f in failures:
        print("  ", f)
else:
    print("All semantic pairings pass in both modes.")

print("\nHalation guard:")
print(f"  dark text {DARK['text']} on {DARK['bg']} = {contrast(DARK['text'], DARK['bg']):.2f}:1")


def emit_css(path="tokens.css"):
    L = []
    w = L.append
    w("/* Imaginars Club Services -- design tokens v3")
    w("   GENERATED BY palette.py. Do not hand-edit; edit the ramps and re-run.")
    w("   Every pairing below is verified against WCAG 2.2 AA by palette.py.")
    w("")
    w("   Tier 1 primitives are never referenced by components.")
    w("   Components may reference ONLY tier-2 semantic tokens. */")
    w("")
    w(":root {")
    w("  /* ---- TIER 1: PRIMITIVES ---- */")
    for k, v in n.items():
        w(f"  --neutral-{k}: {v};")
    w("")
    for k, v in b.items():
        w(f"  --brand-{k}: {v};")
    w("")
    for k, v in s.items():
        w(f"  --{k}: {v};")
    w("")
    w("  /* spacing */")
    for i, px in enumerate([4, 8, 12, 16, 24, 32, 48, 64, 96, 128, 160, 224], start=1):
        w(f"  --space-{i}: {px / 16:.3f}rem;   /* {px}px */")
    w("")
    w("  /* radius */")
    for name, px in (("xs", 4), ("sm", 6), ("md", 10), ("lg", 14), ("xl", 20), ("full", 999)):
        w(f"  --radius-{name}: {px}px;")
    w("")
    w("  /* type scale -- ratio 1.333 */")
    for name, px, track, lead in (
        ("caption", 12, "0.01em", "1.4"), ("small", 14, "0", "1.5"),
        ("body", 16, "-0.005em", "1.6"), ("body-lg", 21, "-0.005em", "1.6"),
        ("h4", 28, "-0.015em", "1.25"), ("h3", 37, "-0.025em", "1.15"),
        ("h2", 50, "-0.025em", "1.08"), ("h1", 67, "-0.035em", "1.02"),
        ("display", 89, "-0.035em", "0.98"),
    ):
        w(f"  --text-{name}: {px / 16:.4f}rem;  --track-{name}: {track};  --lead-{name}: {lead};")
    w("")
    w("  /* motion */")
    w("  --ease-standard: cubic-bezier(0.4, 0, 0.2, 1);")
    w("  --ease-decel: cubic-bezier(0, 0, 0.2, 1);")
    w("  --ease-accel: cubic-bezier(0.4, 0, 1, 1);")
    w("  --ease-emphasis: cubic-bezier(0.2, 0, 0, 1);")
    w("  --dur-micro: 100ms;  --dur-hover: 160ms;  --dur-pop: 200ms;")
    w("  --dur-panel: 300ms;  --dur-view: 420ms;   --stagger: 40ms;")
    w("}")
    w("")

    def block(selector, tokens, extra=()):
        w(f"{selector} {{")
        w(f"  color-scheme: {'dark' if 'dark' in selector else 'light'};")
        for k, v in tokens.items():
            w(f"  --color-{k}: {v};")
        for line in extra:
            w(f"  {line}")
        w("}")
        w("")

    light_extra = (
        "--shadow-1: 0 1px 2px rgba(7,9,14,.04), 0 2px 4px rgba(7,9,14,.03);",
        "--shadow-2: 0 1px 2px rgba(7,9,14,.04), 0 4px 8px rgba(7,9,14,.04), 0 16px 32px rgba(7,9,14,.06);",
        "--shadow-3: 0 1px 2px rgba(7,9,14,.05), 0 8px 16px rgba(7,9,14,.05), 0 24px 48px rgba(7,9,14,.08);",
        "--inset-highlight: none;",
    )
    dark_extra = (
        "--shadow-1: none;",
        "--shadow-2: none;",
        "--shadow-3: 0 16px 48px rgba(0,0,0,.5);",
        "--inset-highlight: inset 0 1px 0 rgba(255,255,255,.06);",
    )

    block(':root, [data-theme="light"]', LIGHT, light_extra)
    block('[data-theme="dark"]', DARK, dark_extra)

    w("@media (prefers-color-scheme: dark) {")
    w("  :root:not([data-theme]) {")
    w("    color-scheme: dark;")
    for k, v in DARK.items():
        w(f"    --color-{k}: {v};")
    for line in dark_extra:
        w(f"    {line}")
    w("  }")
    w("}")
    w("")
    w(":where(a, button, input, select, textarea, summary, [tabindex]):focus-visible {")
    w("  outline: none;")
    w("  box-shadow: 0 0 0 2px var(--color-bg), 0 0 0 4px var(--color-focus-ring);")
    w("  border-radius: var(--radius-sm);")
    w("}")
    w("")
    w("::selection { background: var(--color-accent); color: var(--color-accent-fg); }")
    w("")
    w("@media (prefers-reduced-motion: reduce) {")
    w("  *, *::before, *::after {")
    w("    animation-duration: 0.01ms !important;")
    w("    animation-iteration-count: 1 !important;")
    w("    transition-duration: 0.01ms !important;")
    w("    scroll-behavior: auto !important;")
    w("  }")
    w("}")
    with open(path, "w") as f:
        f.write("\n".join(L) + "\n")
    print(f"\nWrote {path} ({len(L)} lines)")


if __name__ == "__main__":
    emit_css()
